version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    container_name: CORE3
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html
#    environment:
#      - JWT_SECRET=supersecretkey123